### ISSUE TITLE
Is building from source for linux still working

### ISSUE THREAD

**Issue by ghost** [kanryu/quickviewer#158]
Im very new with linux so you'll have to bear with me if I've done anything very wrong.
I've been following the HowToBuild.md but i'm getting errors while trying to build.
I tried the "for QTCreator" and "for command line builders" but they both gave a bunch of errors, here is the QTCreator output
![Screenshot from 2020-12-17 19-31-25](https://user-images.githubusercontent.com/44310349/102462939-8d9fc280-409e-11eb-9401-328fbbc63066.png)
My build steps are 
![image](https://user-images.githubusercontent.com/44310349/102463018-a5774680-409e-11eb-8637-a500ee173b6e.png)
and I use ctrl+b to build
I've commented out `DEFINES += QV_WITHOUT_OPENGL` and `DEFINES += QV_PORTABLE` in QVproject.pri

**Comment by kanryu** [comment]
I've never seen this compilation error. I think it's probably due to the gcc version rather than the Linux version. I think it is effective to add a compile option to prevent error detection or lower the version of gcc.

If you know how to fix the source code to prevent this compilation error, please send me a pull request :)

**Comment by qanatozp** [comment]
> 
> 
> I've never seen this compilation error. I think it's probably due to the gcc version rather than the Linux version. I think it is effective to add a compile option to prevent error detection or lower the version of gcc.
> 
> If you know how to fix the source code to prevent this compilation error, please send me a pull request :)

What environment used for 1.1.1?
Got same error when tried to build with Ubuntu 20.04 default qt5 installation from repositories.

**Comment by kanryu** [comment]
finished ;)
